[package]
name = "hello_cargo"
version = "0.1.0"
authors = ["realMrBread"]
edition = "2020"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
